### ISSUE TITLE
Rename motors

### ISSUE THREAD

**Issue by Floppy** [tehviking/brick_pi_ruby#2]
The internal code talks about motor 1,2,3, and 4, but the normal BrickPi naming uses ABCD for motors. Should they be renamed?

**Comment by tehviking** [comment]
I like this change. At first I was trying to get away from coupling too closely to the initial C implementation but I think this makes sense. Like I want to label the motors and sensors so no one forgets which one is being assigned, and ABCD is the right call here. If you submit a PR I'll merge.
